CREATE DATABASE fintrack;
USE fintrack;
CREATE TABLE user (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
img VARCHAR(255) ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE transaction (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
type ENUM('income','expense') NOT NULL,
amount INT NOT NULL,
category VARCHAR(50) NOT NULL,
date DATE NOT NULL,
description VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user(id)
);
CREATE TABLE budget (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
month VARCHAR(50) NOT NULL,
amount INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user(id)
);
SELECT*FROM user;
SELECT*FROM transaction;
SELECT*FROM budget;

